WITH SRC AS (
    SELECT *
    FROM {{source ('pos','menu')}}
),

TRANSFORMED_PRODUCT AS (
    SELECT
        MENU_ITEM_ID AS PRODUCT_ID,
        MENU_ITEM_NAME AS PRODUCT_NAME,
        ITEM_CATEGORY AS PRODUCT_CATEGORY,
        ITEM_SUBCATEGORY AS PRODUCT_SUBCATEGORY,
    FROM SRC
)

SELECT *
FROM TRANSFORMED_PRODUCT