WITH SRC AS (
    SELECT *
    FROM {{source ('pos','order_detail')}}
),

TRANSFORMED_ORDER_DETAIL AS (
    SELECT
        ORDER_DETAIL_ID,
        ORDER_ID,
        MENU_ITEM_ID AS PRODUCT_ID,
        QUANTITY,
        UNIT_PRICE,
        PRICE AS TOTAL_PRICE,
        DISCOUNT_ID,
        ORDER_ITEM_DISCOUNT_AMOUNT AS ORDER_PRODUC_DISC_AMOUNT,
        LINE_NUMBER,
    FROM SRC
)

SELECT *
FROM TRANSFORMED_ORDER_DETAIL