WITH SRC AS (
    SELECT *
    FROM {{source ('pos','menu')}}
),

TRANSFORMED_PRODUCT AS (
    SELECT
        COST_OF_GOODS_USD AS COST_GOODS_USD,
        MENU_ID,
        MENU_ITEM_ID AS PRODUCT_ID,
        MENU_ITEM_NAME AS PRODUCT_NAME,
        ITEM_CATEGORY AS PRODUCT_CATEGORY,
        ITEM_SUBCATEGORY AS PRODUCT_SUBCATEGORY,
        MENU_ITEM_HEALTH_METRICS_OBJ AS LIST_MENU_ITEM_HEALTHMETRICS,
        MENU_TYPE,
        MENU_TYPE_ID,
        SALE_PRICE_USD,
        TRUCK_BRAND_NAME
    FROM SRC
)

SELECT *
FROM TRANSFORMED_PRODUCT